
development:
  adapter: postgresql
  encoding: unicode
  database: story_overflow_development



test:
  adapter: postgresql
  encoding: unicode
  database: story_overflow_test



production:
  adapter: postgresql
  encoding: unicode
  database: story_overflow_production


